[config]
	base_dir="/dcache/sling.si/projects/intertwin/cmip6_scenarios/"
    cmip6_scenario="ssp126"
[data]
	[data.drivers]
		[data.drivers.lai]
			cmip6_path="lai/[scenario]"
			aggregation="median"
			seafire_name="lai"
			type="dynamic"
		[data.drivers.tasmax]
			cmip6_path="tasmax/[scenario]"
			aggregation="median"
			seafire_name="lst_day"
			type="dynamic"
		[data.drivers.hur]
			cmip6_path="hur/[scenario]"
			aggregation="median"
			seafire_name="rel_hum"
			type="dynamic"
		[data.drivers.tasmin]
			cmip6_path="tasmin/[scenario]"
			aggregation="median"
			seafire_name="t2m_min"
			type="dynamic"
		[data.drivers.pr]
			cmip6_path="pr/[scenario]"
			aggregation="sum"
			seafire_name="pr"
			type="dynamic"
		[data.drivers.sftlf]
			cmip6_path="sftlf/"
			aggregation="None"
			seafire_name="lsm"
			type="static"
