[base]
cuda_availability = "torch.cuda.is_available()"
accelerator = 'cuda'
matmul_precision = 'medium'


[model]
#strategy = "FSDPStrategy(sharding_strategy=ShardingStrategy.FULL_SHARD)"
strategy = "DDPStrategy()"
loss = "torch.nn.BCELoss()"

# metrics = "[]" # "[torch.nn.MSELoss()]"

	[model.dir]
	RUN_DIR = "os.path.join(EXPS_DIR, _today)"
	CHECKPOINTS_DIR = "os.path.join(RUN_DIR, 'checkpoints')"
	SKIP_DAYS_DIRNAME = "skip_days_00"

	[model.unetpp]
	cls = 'Fires._models.unetpp.UnetPlusPlus'
		[model.unetpp.args]
		input_shape = [720, 1440, 8]
		num_classes = 1
		depth = 4
		base_filter_dim = 64
		deep_supervision = false

[metrics]
    [metrics.accuracy]
        target = "torchmetrics::Accuracy"
        task = "binary"
    [metrics.auroc]
        target = "torchmetrics::AUROC"
        task = "binary"
    [metrics.precision]
        target = "torchmetrics::Precision"
        task = "binary"
    [metrics.recall]
        target = "torchmetrics::Recall"
        task = "binary"
    [metrics.f1]
        target = "torchmetrics::F1Score"
        task = "binary"
    [metrics.fbeta]
        target = "torchmetrics::FBetaScore"
        task = "binary"
        beta = 2.0

[trainer]
accumulation_steps = 1
devices = 4
workers = 1
epochs = 75
num_nodes = 1
precision = '32-true'
batch_size = 2
drop_reminder = true
plugins = "[MPIEnvironment()]"
use_distributed_sampler = "False"

	[trainer.optim]
	cls = "torch.optim.Adam"
	args = "dict(lr=1e-4, betas=[0.9, 0.999])"

	[trainer.scheduler]
	cls = "None"
	args = "None"

	[trainer.checkpoint]
	ckpt = "None"


